### ISSUE TITLE
Use PNPM over Yarn

### ISSUE THREAD

**Issue by TKDev7** [psychobolt/vite-storybook-boilerplate#227]
Consider switching to pnpm over yarn

**Comment by psychobolt** [comment]
@MrHBS 

Right now most of my investment is improving Vite-Storybook infrastructure and Yarn has been essential for me so far. Yarn also has a fair set of workspace tools and plugins. As for performance, that really depends on how Yarn is setup for your project. Of course all setups has its own fair share of technical difficulties. If there is something that is not working for you, please create an issue so we can track and hopefully fix your problem. That said, the issue you created is not a problem, but a suggestion to switching to an entirely different solution which could potentially also have its own share of issues. Thus, not a priority.

**Comment by psychobolt** [comment]
So far the setup defaults to Yarn's PnP. There is current investigation to support PNPM resolution, but using Yarn setup: https://github.com/psychobolt/vite-storybook-boilerplate/issues/483
